service: vercel-aws-benchmarker
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
functions:
  benchmark:
    environment:
      COLD_START_LAMBDA: ${env:COLD_START_LAMBDA}
      COLD_START_VERCEL: ${env:COLD_START_VERCEL}
      COLD_START_VERCEL_OLD_RUNTIME: ${env:COLD_START_VERCEL_OLD_RUNTIME}
      COLD_START_HONO: ${env:COLD_START_HONO}
      COLD_START_LWA: ${env:COLD_START_LWA}
    handler: handler.benchmark
    events:
      - schedule: rate(15 minutes)
